[app]
serverport = "9191"
jwtsecret = "^SAghf4553I*&"
log_path = "/home/ped/goprojects/src/skripsi-sso/log" #directory for log
export_path = "/temp"

[[databases]]
name = "db_master"
driver_name = "postgres"
connection_string = "postgres://postgres:root@localhost:5432/db_master?sslmode=disable"
max_connection_open = 20